# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.paperSize = 10
summaryLength = 0

[outputs]
home = ["HTML", "RSS", "JSON"]
