defaultContentLanguage = "en"
enableRobotsTXT = true
pagination.paperSize = 10
summaryLength = 0

[outputs]
home = ["HTML", "RSS", "JSON"]

[privacy.vimeo]
enableDNT = true

[privacy.x]
enableDNT = true

[privacy.youTube]
privacyEnhanced = true

[services.x]
disableInlineCSS = true