[[main]]
name = "impact"
url = "/impact/"
weight = 20

[[main]]
name = "writings"
url = "/writings/"
weight = 10

[[main]]
name = "tools"
url = "/tools/"
weight = 30

[[main]]
identifier = "search"
weight = 99

[main.params]
action = "search"
