# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "cv"
url = "https://docs.google.com/document/d/1ULfaUKOO4E5eGTznVB8WbAGhDlDtZgsJ5umLocBdcL8/edit?usp=sharing"
weight = 60
[main.params]
target = "_blank"

[[main]]
name = "projects"
url = "/projects/"
weight = 50

[[main]]
name = "experience"
url = "/experience/"
weight = 40

[[main]]
name = "tools"
url = "/tools/"
weight = 30

[[main]]
identifier = "search"
weight = 99

[main.params]
action = "search"
